#Testing, #Jest 

[Repo](https://github.com/pozafly/Jest-Example)

만약 계산기가 100 이상 넘는 숫자라면 error가 발생한다고 해보자.

```js
add(num) {
  const sum = this.value + num;
  if (sum > 100) {
    throw new Error('Value can not be greater than 100');
  }
  this.value = sum;
}
```

이렇게 watchAll로 jest를 돌려보면,
<img width="676" alt="image" src="https://user-images.githubusercontent.com/59427983/194761505-196bfb3c-2d89-499c-b845-87a1302105fd.png">
**Uncovered Line** 이라는 칸에 붉은 색으로 무언가 표시된다. -> 17-18 라인은 테스트할 수 있는 코드가 없다라고 나오는 것임.

```js
it('add should throw an error if value is greater than 100', () => {
  expect(() => {
    cal.add(101);
  }).toThrow('Value can not be greater than 100');
});
```
이렇게 expect 함수에 값이 아니라, 콜백 함수로 값을 표현할 수 있고, `toThrow` 함수로 어떤 에러인지를 적어줄 수 있다.